# Generated by Django 4.0.3 on 2022-04-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='avatar',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m'),
        ),
    ]
