# Generated by Django 4.0.3 on 2022-04-12 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0002_category_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rating', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='avatar',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(upload_to='users/%Y/%m'),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('sku', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('color', models.CharField(max_length=100)),
                ('saleOff', models.FloatField(null=True)),
                ('onStock', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eCommercialApi.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eCommercialApi.category'),
        ),
    ]
