# Generated by Django 4.0.3 on 2022-05-12 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0003_alter_bookmarkdetail_productattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarkdetail',
            name='productAttribute',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='bookmarkDetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productAttribute', to='eCommercialApi.bookmarkdetail'),
        ),
    ]
