# Generated by Django 4.0.3 on 2022-04-12 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0003_product_rename_avatar_category_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='category',
            new_name='product',
        ),
    ]
