# Generated by Django 4.0.3 on 2022-04-12 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0004_rename_category_productattribute_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='uploads/%Y/%m')),
                ('productAttr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eCommercialApi.productattribute')),
            ],
        ),
    ]
