# Generated by Django 4.0.3 on 2022-05-12 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0004_remove_bookmarkdetail_productattribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='bookmarkDetail',
        ),
        migrations.AddField(
            model_name='bookmarkdetail',
            name='productAttribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eCommercialApi.productattribute'),
        ),
    ]
