# Generated by Django 4.0.3 on 2022-05-12 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0005_remove_productattribute_bookmarkdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkdetail',
            name='productAttribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookmarkDetail', to='eCommercialApi.productattribute'),
        ),
    ]
