# Generated by Django 4.0.3 on 2022-06-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0006_alter_bookmarkdetail_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_id',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
