# Generated by Django 4.0.3 on 2022-06-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0007_user_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
