# Generated by Django 4.0.3 on 2022-06-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0008_alter_user_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcontact',
            name='district',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shippingcontact',
            name='province',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shippingcontact',
            name='ward',
            field=models.CharField(default='', max_length=255),
        ),
    ]
