# Generated by Django 4.0.3 on 2022-04-12 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0008_bookmark_shippingtype_shippingunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingtype',
            name='shippingUnit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eCommercialApi.shippingunit'),
        ),
    ]
