# Generated by Django 4.0.3 on 2022-06-20 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0009_shippingcontact_district_shippingcontact_province_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingcontact',
            name='address_type',
        ),
    ]
