# Generated by Django 4.0.3 on 2022-04-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0009_shippingtype_shippingunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='productatribute', to='eCommercialApi.bookmark'),
        ),
        migrations.DeleteModel(
            name='BookmarkDetail',
        ),
    ]
