# Generated by Django 4.0.3 on 2022-04-13 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0010_productattribute_bookmarks_delete_bookmarkdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='product',
            new_name='productAttribute',
        ),
    ]
