# Generated by Django 4.0.3 on 2022-06-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0010_remove_shippingcontact_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingcontact',
            name='default_address',
        ),
        migrations.AddField(
            model_name='user',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
    ]
