# Generated by Django 4.0.3 on 2022-04-13 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0011_rename_product_orderdetail_productattribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliveryPrice',
            new_name='delivery_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippedDate',
            new_name='shipped_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippedPrice',
            new_name='shipped_price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingType',
            new_name='shipping_type',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='totalPrice',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='productAttribute',
            new_name='product_attribute',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='unitPrice',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='onStock',
            new_name='on_stock',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='saleOff',
            new_name='sale_off',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='productAttr',
            new_name='product_attr',
        ),
        migrations.RenameField(
            model_name='shippingcontact',
            old_name='addressType',
            new_name='address_type',
        ),
        migrations.RenameField(
            model_name='shippingcontact',
            old_name='defaultAddress',
            new_name='default_address',
        ),
        migrations.RenameField(
            model_name='shippingtype',
            old_name='maxDate',
            new_name='max_date',
        ),
        migrations.RenameField(
            model_name='shippingtype',
            old_name='minDate',
            new_name='min_date',
        ),
        migrations.RemoveField(
            model_name='shippingtype',
            name='shippingUnit',
        ),
        migrations.AddField(
            model_name='shippingtype',
            name='price_per_Km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='shippingtype',
            name='shipping_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eCommercialApi.shippingunit'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='categories/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to='products/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='shippingunit',
            name='image',
            field=models.ImageField(null=True, upload_to='shipping units/%Y/%m'),
        ),
    ]
