# Generated by Django 4.0.3 on 2022-04-13 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0012_rename_deliveryprice_order_delivery_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='image_outline',
        ),
    ]
