# Generated by Django 4.0.3 on 2022-06-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0014_remove_order_delivery_price_remove_order_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.ManyToManyField(to='eCommercialApi.orderdetail'),
        ),
    ]
