# Generated by Django 4.0.3 on 2022-04-13 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0015_category_image_solid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='bookmarks',
        ),
        migrations.CreateModel(
            name='BookmarkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eCommercialApi.bookmark')),
                ('productAttribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eCommercialApi.productattribute')),
            ],
        ),
    ]
