# Generated by Django 4.0.3 on 2022-04-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0016_remove_productattribute_bookmarks_bookmarkdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_outline',
            field=models.ImageField(default=None, upload_to='img/categories/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_solid',
            field=models.ImageField(default=None, upload_to='img/categories/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(null=True, upload_to='img/products/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='shippingunit',
            name='image',
            field=models.ImageField(null=True, upload_to='img/shipping units/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(upload_to='img/users/%Y/%m'),
        ),
    ]
