# Generated by Django 4.0.3 on 2022-04-13 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0017_alter_category_image_outline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='sku',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
