# Generated by Django 4.0.3 on 2022-04-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0018_alter_productattribute_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_attr',
            new_name='productAttribute',
        ),
    ]
