# Generated by Django 4.0.3 on 2022-04-22 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0019_rename_product_attr_productimage_productattribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='eCommercialApi.category'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productAttribute', to='eCommercialApi.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='productAttribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productImage', to='eCommercialApi.productattribute'),
        ),
    ]
