# Generated by Django 4.0.3 on 2022-04-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0021_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='defaultImage',
            field=models.ImageField(null=True, upload_to='img/defaultImageProduct/%Y/%m'),
        ),
    ]
