# Generated by Django 4.0.3 on 2022-04-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0022_product_defaultimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='defaultPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
