# Generated by Django 4.0.3 on 2022-04-26 07:59

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommercialApi', '0024_remove_product_defaultimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='hexColor',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=18, samples=None),
        ),
    ]
